### ISSUE TITLE
vocab.audioblast.org does not resolve

### ISSUE THREAD

**Issue by KatjaSchulz** [audioblast/vocabularies#5]
It looks like https://vocab.audioblast.org/ is down right now.  The server isn't responding.  Are there plans to revive it?  Or even better, could the vocabulary be hosted somewhere on a stable community server?

**Comment by edwbaker** [comment]
We're in the process of moving all audioblast infrastructure to NHM, London - which has been challenging for a few reasons, predominantly the pandemic. So it will be back ASAP.
